### ISSUE TITLE
Choose a managed database + provider 

### ISSUE THREAD

**Issue by JorgeRuizDev** [JorgeRuizDev/SpotMyFM#11]

**Comment by bbaruque** [comment]
¿Cuál es el resultado del estudio?
¿Qué se ha valorado para tomar la decisión?

**Comment by JorgeRuizDev** [comment]
Se han valorado las siguientes bases de datos en la nube:

|                                           | Firestore                    | MongoDB Atlas       | Supabase    | DynamoDB        | Heroku        |
| ----------------------------------------- | ---------------------------- | ------------- | ----------- | --------------- | ------------- |
| Tipo:                                     | Documentos                   | Documentos    | Relacional  | Clave-Valor     | Relacional    |
| Capacidad                                 | 1GB                          | 0.5GB         | 0.5GB       | 25GB            | 1000 filas    |
| Lim. Peticiones                           | 50k R/doc/day 20k W/ doc/day | No hay        | No Hay      | 200M R+W /month |  No Hay             |
| Self-hosted                               | No                           | Si            | Si          | NO              | Si            |
| SSL                                       | Si                           | Si            | Si          | Si              | Si            |
| Escalable                                 | Si                           | Si           | ¿           | Si              | ¿             |
| Pausa                                     | No                           | No            | Si (7 días) | No              | Si (7 días)   |
| ORM/ Bussiness Logic / Model / Validation | No                           | Si (Mongoose) | No          | Si (Dynamoose)  | Si (Postgres) |
| Editor                                    | Si                           | Si            | Si          | Si (De pago)    | Si            |

Resultados:

Heroku no nos da una capacidad lo suficientemente grande como para almacenar todos los datos que queremos.

Firestore tiene unos límites relativamente bajos comparados con el resto de proveedores, aunque extenderlos es relativamente barato. 

Supabase y Firebase no tienen una biblioteca que pueda usarse desde el frontend para tipar / validar las consultas, modelar, etc. Estas herramientas son muy útiles ya que permiten trabajar con datos ya tipados y verificados, agilizando el desarrollo y disminuyendo los errores. 

Por último tenemos MongoDB y DynamoDB, mientras que MongoDB es de código abierto y podemos hostearlo en cualquier cualquier equipo, DynamoDB nos obliga a utilizar Amazon Web Services y no podemos cambiar el proveedor en ningún otro momento. 

Por otro lado, MongoDB Atlas es mucho más caro que DynamoDB, nos ofrece menor capacidad, pero una base de datos mucho más avanzada. 

Como los datos que vamos a almacenar son relativamente simples, DynamoDB parece una opción muy sólida.

**Comment by JorgeRuizDev** [comment]
Para el Hosting se va a utilizar Vercel, el servicio de hosting de Vercel. 

Ofrecen una integración muy sólida con NextJS al ser los desarrolladores del framework, la versión gratuita ofrece muchas horas de Build y ejecución de las funciones serverless, compatibilidad con las características de la última versión de NextJS (12.0), uso de nombre de dominio propios, Build Bots, y otros pequeños detalles. 

Además podemos usar Vercel junto con Github Actions para ejecutar los tests unitarios, integración y sistema del proyecto para evitar despliegues de versiones inestables.

**Comment by JorgeRuizDev** [comment]
Se ha añadido la primera versión funcional de una instancia en beta de la BBDD en el commit bc4c3fe6356b6a060a540a027bcaa7eb2bb3186a.

La velocidad del servicio es bastante buena, pero al ser una base de datos schemeless no se pueden utilizar esquemas dinámicos en tiempo de compilación (pero sí que se puede verificar en ejecución si no utilizamos el tipado estricto)
